'use client';

import html2canvas from 'html2canvas-pro';
import { jsPDF } from 'jspdf';

// Re-export layout constants from dedicated module (keeps heavy deps out of light importers)
export { PDF_LAYOUT } from './pdf-layout';

/**
 * Convert all SVG elements within a container to canvas elements
 * for reliable html2canvas capture. Returns a cleanup function
 * to restore the original SVGs.
 */
async function svgToCanvas(container: HTMLElement): Promise<() => void> {
  const svgs = container.querySelectorAll('svg.recharts-surface');
  const originals: { svg: SVGSVGElement; canvas: HTMLCanvasElement; parent: HTMLElement }[] = [];

  for (const svg of Array.from(svgs)) {
    const svgElement = svg as SVGSVGElement;
    const parent = svgElement.parentElement;
    if (!parent) continue;

    const bbox = svgElement.getBoundingClientRect();
    const canvas = document.createElement('canvas');
    canvas.width = bbox.width * 2; // 2x for retina
    canvas.height = bbox.height * 2;
    canvas.style.width = `${bbox.width}px`;
    canvas.style.height = `${bbox.height}px`;

    const ctx = canvas.getContext('2d');
    if (!ctx) continue;

    // Serialize SVG to string and render to canvas via Image
    const svgData = new XMLSerializer().serializeToString(svgElement);
    const svgBlob = new Blob([svgData], { type: 'image/svg+xml;charset=utf-8' });
    const url = URL.createObjectURL(svgBlob);

    try {
      const img = new Image();
      img.crossOrigin = 'anonymous';
      await new Promise<void>((resolve, reject) => {
        img.onload = () => {
          ctx.scale(2, 2);
          ctx.drawImage(img, 0, 0, bbox.width, bbox.height);
          resolve();
        };
        img.onerror = reject;
        img.src = url;
      });

      // Replace SVG with canvas in DOM
      svgElement.style.display = 'none';
      parent.appendChild(canvas);
      originals.push({ svg: svgElement, canvas, parent });
    } catch {
      // If SVG conversion fails, skip this chart
    } finally {
      URL.revokeObjectURL(url);
    }
  }

  // Return cleanup function
  return () => {
    for (const { svg, canvas, parent } of originals) {
      svg.style.display = '';
      parent.removeChild(canvas);
    }
  };
}

interface ExportBranding {
  logoUrl?: string | null;
  primaryColor?: string | null;
  footerText?: string | null;
  /** When true, removes all Terrain/Ambrosia references (enterprise white-label). */
  whiteLabel?: boolean;
}

interface ExportPdfOptions {
  title: string;
  subtitle?: string;
  filename?: string;
  branding?: ExportBranding;
}

/** Parse a hex color string to RGB values. Returns teal default if invalid. */
function hexToRgb(hex: string | null | undefined): { r: number; g: number; b: number } {
  const DEFAULT = { r: 0, g: 138, b: 116 }; // teal-600
  if (!hex) return DEFAULT;
  const clean = hex.replace('#', '');
  if (!/^[0-9a-fA-F]{3,8}$/.test(clean)) return DEFAULT;
  // Expand shorthand (e.g., "0f8" → "00ff88")
  const full =
    clean.length <= 4
      ? clean
          .split('')
          .map((c) => c + c)
          .join('')
      : clean;
  const num = parseInt(full.slice(0, 6), 16);
  return { r: (num >> 16) & 255, g: (num >> 8) & 255, b: num & 255 };
}

/**
 * Generates a branded PDF from a DOM element.
 * Applies a light export theme before capture, then captures as a
 * high-resolution image and places it in a letter-sized PDF with
 * institutional header and footer.
 */
export async function exportToPdf(element: HTMLElement, options: ExportPdfOptions): Promise<void> {
  const { title, subtitle, filename = 'terrain-report', branding } = options;
  const isWhiteLabel = branding?.whiteLabel === true;
  const accentRgb = hexToRgb(branding?.primaryColor);
  const footerLabel = isWhiteLabel
    ? branding?.footerText || 'CONFIDENTIAL'
    : branding?.footerText || 'CONFIDENTIAL — Generated by Terrain (terrain.ambrosiaventures.co)';

  // ── Apply light export theme for clean paper output ────
  // If already in light mode (e.g., preview overlay), skip the toggle
  const alreadyLight = element.classList.contains('export-light');
  if (!alreadyLight) {
    element.classList.add('export-light');
    await new Promise<void>((resolve) => requestAnimationFrame(() => requestAnimationFrame(() => resolve())));
  }

  // Convert SVG charts to canvas for reliable capture
  const restoreSvgs = await svgToCanvas(element);

  try {
    // Capture at 2x for retina quality with reasonable file sizes (5-10MB vs 30MB+)
    const canvas = await html2canvas(element, {
      scale: 2,
      useCORS: true,
      backgroundColor: '#FFFFFF',
      logging: false,
      windowWidth: 816, // Letter width at 96 DPI
      windowHeight: element.scrollHeight,
      allowTaint: false,
      foreignObjectRendering: false, // More compatible across browsers
    });

    const imgWidth = canvas.width;
    const imgHeight = canvas.height;

    // Letter size in mm
    const pageWidth = 215.9;
    const pageHeight = 279.4;
    const margin = 15;
    const headerHeight = 28;
    const footerHeight = 15;
    const contentWidth = pageWidth - margin * 2;
    const contentHeight = pageHeight - margin * 2 - headerHeight - footerHeight;

    const pdf = new jsPDF({
      orientation: 'portrait',
      unit: 'mm',
      format: 'letter',
    });

    // ── PDF metadata ───────────────────────────────────────
    pdf.setProperties({
      title: isWhiteLabel ? `${title} — Intelligence Report` : `${title} — Terrain Intelligence Report`,
      subject: subtitle || 'Market Intelligence Report',
      author: isWhiteLabel ? 'Intelligence Platform' : 'Terrain by Ambrosia Ventures',
      creator: isWhiteLabel ? 'Intelligence Platform' : 'Terrain (terrain.ambrosiaventures.co)',
      keywords: 'market intelligence, life sciences, biotech',
    });

    // Scale image to fit content width
    const scaleFactor = 2; // Must match html2canvas scale option
    const ratio = contentWidth / (imgWidth / scaleFactor);
    const scaledHeight = (imgHeight / scaleFactor) * ratio;
    const totalPages = Math.ceil(scaledHeight / contentHeight);

    const dateString = new Date().toLocaleDateString('en-US', {
      year: 'numeric',
      month: 'long',
      day: 'numeric',
    });

    for (let page = 0; page < totalPages; page++) {
      if (page > 0) pdf.addPage();

      // ── Header ──────────────────────────────────────────
      pdf.setFillColor(255, 255, 255);
      pdf.rect(0, 0, pageWidth, headerHeight + margin, 'F');

      // Brand — render logo if provided, otherwise text
      let headerTextX = margin;
      if (branding?.logoUrl) {
        try {
          const logoImg = new Image();
          logoImg.crossOrigin = 'anonymous';
          await new Promise<void>((resolve, reject) => {
            logoImg.onload = () => resolve();
            logoImg.onerror = () => reject(new Error('Logo load failed'));
            logoImg.src = branding.logoUrl!;
          });
          const logoCanvas = document.createElement('canvas');
          logoCanvas.width = logoImg.naturalWidth;
          logoCanvas.height = logoImg.naturalHeight;
          const logoCtx = logoCanvas.getContext('2d');
          if (logoCtx) {
            logoCtx.drawImage(logoImg, 0, 0);
            const logoData = logoCanvas.toDataURL('image/png');
            const logoH = 8; // mm height
            const logoW = (logoImg.naturalWidth / logoImg.naturalHeight) * logoH;
            pdf.addImage(logoData, 'PNG', margin, margin + 2, logoW, logoH);
            headerTextX = margin + logoW + 3;
          }
        } catch {
          // Logo failed to load — fall back to text brand
        }
      }
      if (!isWhiteLabel) {
        // Default Terrain branding — distinctive bold italic for brand name
        pdf.setFont('helvetica', 'bolditalic');
        pdf.setFontSize(12);
        pdf.setTextColor(4, 8, 15); // navy-950
        pdf.text('TERRAIN', headerTextX, margin + 7);

        // Tagline
        pdf.setFont('helvetica', 'normal');
        pdf.setFontSize(7);
        pdf.setTextColor(accentRgb.r, accentRgb.g, accentRgb.b);
        pdf.text('by Ambrosia Ventures', headerTextX + 24, margin + 7);

        // Thin line under brand area
        pdf.setDrawColor(209, 213, 219); // gray-300
        pdf.setLineWidth(0.3);
        pdf.line(margin, margin + 10, pageWidth - margin, margin + 10);
      } else if (!branding?.logoUrl) {
        // White-label without logo — show nothing (logo handled above if present)
        // Intentionally blank header brand area
      }

      // Report title — larger for first page, smaller for continuation pages
      pdf.setFont('helvetica', 'bold');
      pdf.setFontSize(page === 0 ? 16 : 10);
      pdf.setTextColor(4, 8, 15);
      pdf.text(title, margin, margin + 16);

      if (subtitle) {
        pdf.setFont('helvetica', 'normal');
        pdf.setFontSize(page === 0 ? 10 : 7);
        pdf.setTextColor(100, 116, 139); // slate-500
        pdf.text(subtitle, margin, margin + (page === 0 ? 22 : 21));
      }

      // Date line on first page
      if (page === 0) {
        pdf.setFont('helvetica', 'normal');
        pdf.setFontSize(8);
        pdf.setTextColor(100, 116, 139);
        pdf.text(`Prepared ${dateString}`, margin, margin + (subtitle ? 27 : 22));
      }

      // Page number
      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(7);
      pdf.setTextColor(100, 116, 139);
      pdf.text(`Page ${page + 1} of ${totalPages}`, pageWidth - margin, margin + 7, { align: 'right' });

      // Accent line (uses branding color if provided)
      pdf.setDrawColor(accentRgb.r, accentRgb.g, accentRgb.b);
      pdf.setLineWidth(0.8);
      pdf.line(margin, headerHeight + margin - 2, pageWidth - margin, headerHeight + margin - 2);

      // ── Content (cropped from the full image) ───────────
      const sourceY = ((page * contentHeight) / ratio) * scaleFactor;
      const sourceH = Math.min((contentHeight / ratio) * scaleFactor, imgHeight - sourceY);

      const pageCanvas = document.createElement('canvas');
      pageCanvas.width = imgWidth;
      pageCanvas.height = sourceH;
      const ctx = pageCanvas.getContext('2d');
      if (ctx) {
        ctx.drawImage(canvas, 0, sourceY, imgWidth, sourceH, 0, 0, imgWidth, sourceH);
        const pageImgData = pageCanvas.toDataURL('image/png');
        const sliceHeight = (sourceH / scaleFactor) * ratio;
        pdf.addImage(pageImgData, 'PNG', margin, headerHeight + margin, contentWidth, sliceHeight);
      }

      // ── Footer (single line: left / center / right) ────
      const footerY = pageHeight - margin - 4;
      pdf.setDrawColor(209, 213, 219); // gray-300
      pdf.setLineWidth(0.3);
      pdf.line(margin, footerY - 4, pageWidth - margin, footerY - 4);

      pdf.setFont('helvetica', 'normal');
      pdf.setFontSize(6);
      pdf.setTextColor(100, 116, 139);
      // Left: confidential label
      pdf.text(
        `CONFIDENTIAL — ${branding?.footerText || (isWhiteLabel ? '' : 'Generated by Terrain (terrain.ambrosiaventures.co)')}`,
        margin,
        footerY,
      );
      // Center: copyright
      pdf.text('\u00A9 2026 Ambrosia Ventures', pageWidth / 2, footerY, { align: 'center' });
      // Right: date + page
      pdf.text(`${dateString}  |  Page ${page + 1} of ${totalPages}`, pageWidth - margin, footerY, { align: 'right' });
    }

    pdf.save(`${filename}.pdf`);
  } finally {
    // Restore original SVG elements
    restoreSvgs();
    // Only remove the class if we added it
    if (!alreadyLight) {
      element.classList.remove('export-light');
    }
  }
}
